# EXPERIMENT 13
## NEHA BHAT
## ENTC A2 - 25070123032
##DATA BINNING ND DAT FORMATIN USING PYTHON

In [ ]:
import pandas as pd
import numpy as np


data={
    'Product':['laptop','mobile','tablet','headphones','smartwatch','camera'],
    'Price':[55000,50000,45000,6000,7000,20000],
    'Units_sold':[20,30,40,50,60,18]

}
df=pd.DataFrame(data)
print("data")
print(df)

data
      Product  Price  Units_sold
0      laptop  55000          20
1      mobile  50000          30
2      tablet  45000          40
3  headphones   6000          50
4  smartwatch   7000          60
5      camera  20000          18

In [ ]:
# DATA BINNING
bins1 =[0,1000,30000,60000]
labels1 =['low','medium','high']
df['Price_category'] =pd.cut(df['Price'],bins=bins1,labels =labels1)
print(df)

      Product  Price  Units_sold Price_category
0      laptop  55000          20           high
1      mobile  50000          30           high
2      tablet  45000          40           high
3  headphones   6000          50         medium
4  smartwatch   7000          60         medium
5      camera  20000          18         medium

In [ ]:

# binning units sold
bins2=[0,10,30,100]
labels2=['less','medium','more']
df['sales category'] = pd.cut(df['Units_sold'],bins=bins2,labels =labels2)
print(df)

      Product  Price  Units_sold Price_category sales category
0      laptop  55000          20           high         medium
1      mobile  50000          30           high         medium
2      tablet  45000          40           high           more
3  headphones   6000          50         medium           more
4  smartwatch   7000          60         medium           more
5      camera  20000          18         medium         medium

In [ ]:
# data formatting
# convert data type
print(df.dtypes)
df['Units_sold']= df['Units_sold'].astype(float)
print(df.dtypes)

Product             object
Price                int64
Units_sold           int64
Price_category    category
sales category    category
dtype: object
Product             object
Price                int64
Units_sold         float64
Price_category    category
sales category    category
dtype: object

In [ ]:
# convert text to uppercase
df['Product']=df['Product'].str.upper()
print(df)

      Product  Price  Units_sold Price_category sales category
0      LAPTOP  55000        20.0           high         medium
1      MOBILE  50000        30.0           high         medium
2      TABLET  45000        40.0           high           more
3  HEADPHONES   6000        50.0         medium           more
4  SMARTWATCH   7000        60.0         medium           more
5      CAMERA  20000        18.0         medium         medium

In [ ]:
# Rounding values
df['Price']=df['Price'].round(2)
print(df)

      Product  Price  Units_sold Price_category sales category
0      LAPTOP  55000        20.0           high         medium
1      MOBILE  50000        30.0           high         medium
2      TABLET  45000        40.0           high           more
3  HEADPHONES   6000        50.0         medium           more
4  SMARTWATCH   7000        60.0         medium           more
5      CAMERA  20000        18.0         medium         medium

In [ ]:

# additional operations
sorted_df=df.sort_values(by='Price')
print(sorted_df)

      Product  Price  Units_sold Price_category sales category
3  HEADPHONES   6000        50.0         medium           more
4  SMARTWATCH   7000        60.0         medium           more
5      CAMERA  20000        18.0         medium         medium
2      TABLET  45000        40.0           high           more
1      MOBILE  50000        30.0           high         medium
0      LAPTOP  55000        20.0           high         medium

In [ ]:
# display unique values
print(df['Price_category'].unique())

['high', 'medium']
Categories (3, object): ['low' < 'medium' < 'high']

In [ ]:
import pandas as pd
import numpy as np
data ={
    'Order_ID':['01','02','03','04','05','06','07','08'],
    'Order_Value':[250,340,490,345,657,789,768,400],
    'Delivery_Time':[30,45,25,60,35,20,50,28],
    'Distance_KM':[3,5,2,6,13,20,58,28],
}
df=pd.DataFrame(data)
print("data")
print(df)

data
  Order_ID  Order_Value  Delivery_Time  Distance_KM
0       01          250             30            3
1       02          340             45            5
2       03          490             25            2
3       04          345             60            6
4       05          657             35           13
5       06          789             20           20
6       07          768             50           58
7       08          400             28           28

In [ ]:
# binning order value
bins2 =[0,200,400,700]
labels2 =['low','medium','high']
df['Order Category']=pd.cut(df['Order_Value'],bins=bins2,labels =labels2)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_KM Order Category
0       01          250             30            3         medium
1       02          340             45            5         medium
2       03          490             25            2           high
3       04          345             60            6         medium
4       05          657             35           13           high
5       06          789             20           20            NaN
6       07          768             50           58            NaN
7       08          400             28           28         medium

In [ ]:
#binning delivery time
bins1=[0,30,45,70]
labels2 =['fast','nrmal','slow']
df['Delivery_speed'] =pd.cut(df['Delivery_Time'],bins=bins1,labels =labels1)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_KM Order Category  \
0       01          250             30            3         medium
1       02          340             45            5         medium
2       03          490             25            2           high
3       04          345             60            6         medium
4       05          657             35           13           high
5       06          789             20           20            NaN
6       07          768             50           58            NaN
7       08          400             28           28         medium

  Delivery_speed
0            low
1         medium
2            low
3           high
4         medium
5            low
6           high
7            low

In [ ]:
# data formatting examples
df['Distance_KM']=df['Distance_KM'].astype(float)
df

,Order_ID,Order_Value,Delivery_Time,Distance_KM,Order Category,Delivery_speed
0,01,250,30,3.0,medium,low
1,02,340,45,5.0,medium,medium
2,03,490,25,2.0,high,low
3,04,345,60,6.0,medium,high
4,05,657,35,13.0,high,medium
5,06,789,20,20.0,NaN,low
6,07,768,50,58.0,NaN,high
7,08,400,28,28.0,medium,low

In [ ]:
# convert id to uppercase
df['Order Category']=df['Order Category'].str.upper()
df

,Order_ID,Order_Value,Delivery_Time,Distance_KM,Order Category,Delivery_speed
0,01,250,30,3.0,MEDIUM,low
1,02,340,45,5.0,MEDIUM,medium
2,03,490,25,2.0,HIGH,low
3,04,345,60,6.0,MEDIUM,high
4,05,657,35,13.0,HIGH,medium
5,06,789,20,20.0,NaN,low
6,07,768,50,58.0,NaN,high
7,08,400,28,28.0,MEDIUM,low

In [ ]:
# check data types
print(df.dtypes)

Order_ID            object
Order_Value          int64
Delivery_Time        int64
Distance_KM        float64
Order Category      object
Delivery_speed    category
dtype: object

In [ ]:
#unique categories
print(df['Order Category'].unique())
df

['MEDIUM' 'HIGH' nan]

,Order_ID,Order_Value,Delivery_Time,Distance_KM,Order Category,Delivery_speed
0,01,250,30,3.0,MEDIUM,low
1,02,340,45,5.0,MEDIUM,medium
2,03,490,25,2.0,HIGH,low
3,04,345,60,6.0,MEDIUM,high
4,05,657,35,13.0,HIGH,medium
5,06,789,20,20.0,NaN,low
6,07,768,50,58.0,NaN,high
7,08,400,28,28.0,MEDIUM,low

In [ ]:
# count of categories
print(df['Order Category'].value_counts())
df

Order Category
MEDIUM    4
HIGH      2
Name: count, dtype: int64

,Order_ID,Order_Value,Delivery_Time,Distance_KM,Order Category,Delivery_speed
0,01,250,30,3.0,MEDIUM,low
1,02,340,45,5.0,MEDIUM,medium
2,03,490,25,2.0,HIGH,low
3,04,345,60,6.0,MEDIUM,high
4,05,657,35,13.0,HIGH,medium
5,06,789,20,20.0,NaN,low
6,07,768,50,58.0,NaN,high
7,08,400,28,28.0,MEDIUM,low

In [ ]:
# sorting
print(df.sort_values(by='Order_Value'))

  Order_ID  Order_Value  Delivery_Time  Distance_KM Order Category  \
0       01          250             30          3.0         MEDIUM
1       02          340             45          5.0         MEDIUM
3       04          345             60          6.0         MEDIUM
7       08          400             28         28.0         MEDIUM
2       03          490             25          2.0           HIGH
4       05          657             35         13.0           HIGH
6       07          768             50         58.0            NaN
5       06          789             20         20.0            NaN

  Delivery_speed
0            low
1         medium
3           high
7            low
2            low
4         medium
6           high
5            low